In [35]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [36]:
from classes_n import *
from main import *


demand_p1 = Demand(P1)

combined_p1 = Inventory(demand_p1)


In [37]:
print(INVENTORY_MODE)

combined_p1.inventory_level


2


[378290]

In [38]:
combined_p1.put(100)
combined_p1.get(50)
combined_p1.inventory_level

[378290, 378390, 378340]

### Testing the warehouse

In [39]:
demand_p1, demand_p2 = Demand(P1), Demand(P2)

combined_p1, combined_p2 = Inventory(demand_p1), Inventory(demand_p2)

warehouse = Warehouse(combined_p1, combined_p2)

In [40]:
order = {"product":"p1", "amount": 40_000_000}

In [41]:
warehouse.current_warehouse_level

18805097

In [42]:
warehouse.is_possible_to_store(order)

False

### Testing the Inventory class inside the Warehouse

In [43]:
warehouse.products[1].inventory_level

[18418462]

### Testing Demand class inside the Warehouse

In [44]:
warehouse.products[1].demand_class.demand

array([      0.,       0.,       0.,  223654.,  295269.,       0.,
        721844.,       0.,       0., 1463733.,       0.,       0.,
             0.,  968580.,  463215.,       0., 1655813.,       0.,
             0.,  659732.,       0.,  431042.,       0., 1923954.,
             0.,  483903.,  232350.,       0.,       0.,       0.,
             0.,       0.,  230008.,  976298., 1191033.,       0.,
       1401510.,       0.,  709791., 1042305., 1353245.,       0.,
             0., 1053069.,       0., 1054610.,       0.,  776955.,
        406003.,  433453.,       0.,       0.,       0.,  950532.,
             0.,  522510.,       0.,       0., 1016839.,       0.,
        520142.,       0., 1698093.,       0.,  839677.,  473293.,
             0.,  739734.,       0.,  658379.,  620833.,       0.,
        715438.,       0.,       0.,  925270.,  982839.,  294984.,
        773272.,       0., 1218866.,       0.,       0.,       0.,
       1129966., 1457216.,       0., 1509158.,       0.,  8490

### Testing Machine class

In [45]:
machine = Machine(warehouse)

In [46]:
order = {"product": "p1", "amount": 10_000}

In [47]:
#machine.is_possible_to_produce(order)

In [48]:
machine.produce(order)
machine.produce(order)
machine.produce(order)
machine.produce(order)

0

In [49]:
warehouse.products[0].inventory_level

[386635, 396635, 406635, 416635, 426635]

In [50]:
warehouse.products[1].inventory_level

[18418462, 18418462, 18418462, 18418462, 18418462]

In [63]:
machine.fulfill(10)

10

In [64]:
warehouse.products[0].inventory_level

[386635,
 396635,
 406635,
 416635,
 426635,
 426635,
 426635,
 426635,
 426635,
 426635]

In [65]:
warehouse.products[1].inventory_level

[18418462,
 18418462,
 18418462,
 18418462,
 18418462,
 18418462,
 18418462,
 18418462,
 18418462,
 18418462]

In [54]:
import numpy as np
np.random.lognormal(254.629, 1)
lognorm_int(254.629, 1)

array([274.])

In [55]:
mu0 = 100_000_000 * (0.22/86400)
sigma0 = 10e-5

mu = np.log(mu0**2 / np.sqrt(sigma0**2 + mu0**2))
sigma = np.sqrt(np.log(sigma0**2 / mu0**2 + 1))

print(np.mean(np.random.lognormal(mu, sigma, 100000)))
print(np.mean(lognorm_int(mu0, sigma0, size=100000)))

254.62962923797372
255.0


In [56]:
# Profs code
def lognorm(mu, varcoef) -> float:
    """
    scales the target expected value mu and varcoef = sigma/mu to the 
    embedded normal distribution with mu0 and sigma0 and returns
    the corresponding output
    beauty of lognorm: is always > 0 
    """
    mu0 = np.log(mu / np.sqrt(np.power(varcoef, 2) + 1.0))
    sigma0 = np.sqrt(np.log(np.power(varcoef, 2) + 1.0))
    return random.lognormvariate(mu0, sigma0)

sum = 0
for i in range(100000):
    sum += lognorm(mu0, sigma0)
print(sum/100000)

254.62973102245024


In [57]:
not 1

False

### Testing the environment

In [66]:
from environment_ddpg_n import *

In [67]:
env = Production_DQN_Env()

In [72]:
env.machine.warehouse.current_warehouse_level

19825801

In [31]:
import gym
from gym import spaces
import numpy as np

test_box = spaces.Box(low=0, high=10, dtype=np.int32)
#possible idea for the action space:
test_box_2 = spaces.Tuple(
    (spaces.Discrete(2), spaces.Box(low=0, high=300000, dtype=np.int32))
)

test_box_3 = spaces.Tuple(
    (spaces.Discrete(2), spaces.Discrete(3))
)

test_box_4 = spaces.Dict(
    {
        "a": spaces.Discrete(2), 
        "b": spaces.Discrete(3)
    }
)

print(spaces.utils.flatdim(test_box_2))
print(spaces.utils.flatten_space(test_box_4))
print(spaces.utils.flatten(test_box_4, test_box_4.sample()))
print(test_box_4.shape)

3
Box(0, 1, (5,), int64)
[1 0 0 1 0]
None


In [29]:
test_box_2.sample()[1][0]

251453

In [36]:
import ..environment_Alex.base_functions


SyntaxError: invalid syntax (171344864.py, line 1)