In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
from classes_n import *
from main import *


demand_p1 = Demand(P1)

combined_p1 = Inventory(demand_p1)


In [22]:
print(INVENTORY_MODE)

combined_p1.inventory_level


2


[382714]

In [23]:
combined_p1.put(100)
combined_p1.get(50)
combined_p1.inventory_level

[382714, 382764]

### Testing the warehouse

In [72]:
demand_p1, demand_p2 = Demand(P1), Demand(P2)

combined_p1, combined_p2 = Inventory(demand_p1), Inventory(demand_p2)

warehouse = Warehouse(combined_p1, combined_p2)

In [73]:
#order = {"product":"p1", "amount": 40_000_000}
order = [0, 10_000]

In [74]:
warehouse.current_warehouse_level

18090447

In [76]:
warehouse.is_possible_to_store(order)

True

### Testing the Inventory class inside the Warehouse

In [77]:
warehouse.products[1].inventory_level

[17686910]

### Testing Demand class inside the Warehouse

In [78]:
warehouse.products[1].demand_class.demand

array([      0., 1406581.,       0.,  719913.,  677924.,  603457.,
             0.,       0.,       0.,       0.,   89281.,       0.,
             0.,       0., 1086347.,       0.,       0., 3180785.,
        445071.,       0.,  765988.,       0.,  419111.,       0.,
             0.,  455808.,       0.,  124390., 1037908.,       0.,
       3215070.,       0.,       0.,       0., 1135721.,       0.,
        155899., 1323128.,       0.,  539083.,       0., 1941836.,
        369538.,       0.,  686057., 1128795.,       0.,       0.,
        667263.,       0.,  509582.,  674280.,       0.,       0.,
        279732.,       0.,  702633.,       0.,       0., 1280022.,
        856716.,       0.,       0.,  485028.,  835735.,  446885.,
             0.,       0.,       0.,  940311.,  333373.,       0.,
        899582.,       0.,  468743.,  442283.,  751439.,  601159.,
       1889877.,       0., 1198029.,  641432.,       0.,       0.,
       2163658.,       0.,       0.,       0.,  993915.,  4541

### Testing Machine class

In [79]:
machine = Machine(warehouse)

In [80]:
#order = {"product": "p1", "amount": 10_000}
order = [0, 10_000]

In [81]:
machine.is_possible_to_produce(order)

True

In [82]:
machine.produce(order)
machine.produce(order)
machine.produce(order)
machine.produce(order)

0

In [83]:
warehouse.products[0].inventory_level

[403537, 413537, 423537, 433537, 443537]

In [85]:
warehouse.products[1].inventory_level

[17686910, 17686910, 17686910, 17686910, 17686910]

In [87]:
machine.fulfill(10)

10

In [88]:
warehouse.products[0].inventory_level

[403537, 413537, 423537, 433537, 443537]

In [89]:
warehouse.products[1].inventory_level

[17686910, 17686910, 17686910, 17686910, 17686910]

In [39]:
import numpy as np
np.random.lognormal(254.629, 1)
lognorm_int(254.629, 1)

array([78.])

In [40]:
mu0 = 100_000_000 * (0.22/86400)
sigma0 = 10e-5

mu = np.log(mu0**2 / np.sqrt(sigma0**2 + mu0**2))
sigma = np.sqrt(np.log(sigma0**2 / mu0**2 + 1))

print(np.mean(np.random.lognormal(mu, sigma, 100000)))
print(np.mean(lognorm_int(mu0, sigma0, size=100000)))

254.62962948033075
255.0


In [41]:
# Profs code
def lognorm(mu, varcoef) -> float:
    """
    scales the target expected value mu and varcoef = sigma/mu to the 
    embedded normal distribution with mu0 and sigma0 and returns
    the corresponding output
    beauty of lognorm: is always > 0 
    """
    mu0 = np.log(mu / np.sqrt(np.power(varcoef, 2) + 1.0))
    sigma0 = np.sqrt(np.log(np.power(varcoef, 2) + 1.0))
    return random.lognormvariate(mu0, sigma0)

sum = 0
for i in range(100000):
    sum += lognorm(mu0, sigma0)
print(sum/100000)

254.62953253060624


In [42]:
not 1

False

### Testing the environment

In [2]:
from environment_ddpg_n import *

In [3]:
env = Production_DDPG_Env()

In [92]:
env.machine.warehouse.current_warehouse_level

20181322

In [4]:
env.action_space

MultiDiscrete([       2 50000000])

In [111]:
env.action_space.sample()
env.machine.is_possible_to_produce([1, 1000000000])
env.machine.warehouse.is_possible_to_store([1, 100])

True

In [2]:
import gym
from gym import spaces
import numpy as np

test_box = spaces.Box(low=0, high=10, dtype=np.int32)
#possible idea for the action space:
test_box_2 = spaces.Tuple(
    (spaces.Discrete(2), spaces.Box(low=0, high=300000, dtype=np.int32))
)

test_box_3 = spaces.Tuple(
    (spaces.Discrete(2), spaces.Discrete(3))
)

test_box_4 = spaces.Dict(
    {
        "a": spaces.Discrete(2), 
        "b": spaces.Discrete(3)
    }
)

print(spaces.utils.flatdim(test_box_2))
print(spaces.utils.flatten_space(test_box_4))
print(spaces.utils.flatten(test_box_4, test_box_4.sample()))
print(test_box_4.shape)

3
Box(0, 1, (5,), int64)
[0 1 0 0 1]
None


In [ ]:
test_box_2.sample()[1][0]

251453

In [11]:
test_box_5 = spaces.MultiDiscrete([2, 50_000_000])
test_box_5.sample()

array([       0, 12916977])

In [15]:
env.action_space.sample()

array([       1, 10951471])

In [16]:
env.observation_space.sample()

array([39560669, 11064436,        1, 18677161])

## Testing the full environment

In [56]:
env.step(env.action_space.sample())

((240163.0, 12838986.0, 33849.0, 1658343.0), 0, False, False, {})

In [112]:
env._get_obs()

(391417, 17797815, 0, 0)

In [113]:
env.reset()

((425614, 18681378, 30928, 0), {})

In [116]:
env.action_space.__len__()

2

# Testing utils.py

In [18]:
env.action_space[1].n

50000000

In [21]:
from ddpg_utils import *

gaus = GaussianNoise(env.action_space)

In [22]:
gaus.get_action(env.action_space.sample())

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Users/alex/anaconda3/envs/study/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/alex/anaconda3/envs/study/lib/python3.11/site-packages/numpy/core/_methods.py", line 99, in _clip
    return um.clip(a, min, max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._UFuncInputCastingError: Cannot cast ufunc 'clip' input 0 from dtype('float64') to dtype('int32') with casting rule 'same_kind'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/anaconda3/envs/study/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tx/v7tzcb5x7dj1jn2y987ft2m80000gn/T/ipykernel_2346/2918755287.py", line 1, in <module>
    gaus.get_action(