In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from classes_n import *
from main import *


demand_p1 = Demand(P1)

combined_p1 = Inventory(demand_p1)


ModuleNotFoundError: No module named 'main'

In [ ]:
print(INVENTORY_MODE)

combined_p1.inventory_level


2


[403426]

In [ ]:
combined_p1.put(100)
combined_p1.get(50)
combined_p1.inventory_level

[390879, 390929]

### Testing the warehouse

In [ ]:
demand_p1, demand_p2 = Demand(P1), Demand(P2)

combined_p1, combined_p2 = Inventory(demand_p1), Inventory(demand_p2)

warehouse = Warehouse(combined_p1, combined_p2)

In [ ]:
#order = {"product":"p1", "amount": 40_000_000}
order = [0, 10_000]

In [ ]:
warehouse.current_warehouse_level

18422789

In [ ]:
warehouse.is_possible_to_store(order)

True

### Testing the Inventory class inside the Warehouse

In [ ]:
warehouse.products[1].inventory_level

[18035362]

### Testing Demand class inside the Warehouse

In [ ]:
warehouse.products[1].demand_class.demand

array([      0,  267872,       0,  323477,  500839,       0,       0,
        895557,       0,       0,       0,       0,  470539,       0,
        730020,       0,       0,  248231,  767266,  220383,       0,
        474482,  753917,       0, 1770712,  730416,  655379,  817243,
             0,       0,       0,  867910,       0,       0, 1017545,
       2940514,  497560, 2086639,  977078,  287387, 1051490,       0,
             0, 1534078,  838956,       0,  466768,  186674, 1447425,
             0,  446606, 1343385,       0,       0,  407208,       0,
             0,       0,  390488, 1385229,       0,  339298,       0,
        677076,       0, 1176413, 1549471,  618264, 1530621,       0,
       1071272,  793149,       0, 1245502,       0,       0,       0,
        618503, 1344165,  584019,       0,  523094,       0,       0,
        426594, 1759971,       0,       0,       0,  326813,       0,
        825083, 1894240,       0,  582588, 2498001,       0,  731274,
       1231647,     

### Testing Machine class

In [ ]:
machine = Machine(warehouse)

In [ ]:
#order = {"product": "p1", "amount": 10_000}
order = [0, 10_000]

In [ ]:
machine.is_possible_to_produce(order)

True

In [ ]:
machine.produce(order)
machine.produce(order)
machine.produce(order)
machine.produce(order)

0

In [ ]:
warehouse.products[0].inventory_level

[387427, 397427, 407427, 417427, 427427]

In [ ]:
warehouse.products[1].inventory_level

[18035362, 18035362, 18035362, 18035362, 18035362]

In [ ]:
machine.fulfill()

10

In [ ]:
warehouse.products[0].inventory_level

[387427, 397427, 407427, 417427, 427427]

In [ ]:
warehouse.products[1].inventory_level

[18035362, 18035362, 18035362, 18035362, 18035362]

In [ ]:
import numpy as np
np.random.lognormal(254.629, 1)
lognorm_int(254.629, 1)

array([113.])

In [ ]:
mu0 = 100_000_000 * (0.22/86400)
sigma0 = 10e-5

mu = np.log(mu0**2 / np.sqrt(sigma0**2 + mu0**2))
sigma = np.sqrt(np.log(sigma0**2 / mu0**2 + 1))

print(np.mean(np.random.lognormal(mu, sigma, 100000)))
print(np.mean(lognorm_int(mu0, sigma0, size=100000)))

254.62962970167544
255.0


In [ ]:
# Profs code
def lognorm(mu, varcoef) -> float:
    """
    scales the target expected value mu and varcoef = sigma/mu to the 
    embedded normal distribution with mu0 and sigma0 and returns
    the corresponding output
    beauty of lognorm: is always > 0 
    """
    mu0 = np.log(mu / np.sqrt(np.power(varcoef, 2) + 1.0))
    sigma0 = np.sqrt(np.log(np.power(varcoef, 2) + 1.0))
    return random.lognormvariate(mu0, sigma0)

sum = 0
for i in range(100000):
    sum += lognorm(mu0, sigma0)
print(sum/100000)

254.6297108735997


In [ ]:
not 1

False

### Testing the environment

In [ ]:
from environment_ddpg_n import *

In [ ]:
env = Production_DDPG_Env()

In [ ]:
env.machine.warehouse.current_warehouse_level

19171119

In [ ]:
env.action_space

MultiDiscrete([       2 50000000])

In [ ]:
env.action_space.sample()
env.machine.is_possible_to_produce([1, 1000000000])
env.machine.warehouse.is_possible_to_store([1, 100])

True

In [ ]:
import gym
from gym import spaces
import numpy as np

test_box = spaces.Box(low=0, high=10, dtype=np.int32)
#possible idea for the action space:
test_box_2 = spaces.Tuple(
    (spaces.Discrete(2), spaces.Box(low=0, high=300000, dtype=np.int32))
)

test_box_3 = spaces.Tuple(
    (spaces.Discrete(2), spaces.Discrete(3))
)

test_box_4 = spaces.Dict(
    {
        "a": spaces.Discrete(2), 
        "b": spaces.Discrete(3)
    }
)

print(spaces.utils.flatdim(test_box_2))
print(spaces.utils.flatten_space(test_box_4))
print(spaces.utils.flatten(test_box_4, test_box_4.sample()))
print(test_box_4.shape)

3
Box(0, 1, (5,), int64)
[0 1 1 0 0]
None


In [ ]:
test_box_2.sample()[1][0]

89153

In [ ]:
test_box_5 = spaces.MultiDiscrete([2, 50_000_000])
test_box_5.sample()

array([       1, 35283231])

In [ ]:
env.action_space.sample()

array([       1, 31780193])

In [ ]:
env.observation_space.sample()

array([13752060, 40338683, 11099065, 15214828])

## Testing the full environment

In [ ]:
from environment_ddpg_n import *

env = Production_DDPG_Env()
env.reset()

for i in range(1_000_000):
    if i%100 == 0:
        print(i)
    env.step(env.action_space.sample())

In [ ]:
env._get_obs()

(373315, 17987949, 0, 0)

In [ ]:
env.reset()

((387726, 17560874, 0, 0), {})

In [ ]:
env.action_space.__len__()

2

# Testing utils.py

In [ ]:
env.action_space[1].n

50000000

In [ ]:
from ddpg_utils import *

gaus = GaussianNoise(env.action_space)

In [ ]:
gaus.get_action(env.action_space.sample())

array([       0., 31681329.])

In [ ]:
memory = Memory(1000)

obs_prev, _ = env.reset()

action = env.action_space.sample()

obs, reward, terminated, _, _ = env.step(action)

In [ ]:
for i in range(100):
    memory.push(obs_prev, action, reward, obs, terminated)

In [ ]:
memory.sample(10)

([(402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0),
  (402338, 18927136, 26466, 0)],
 [array([       1, 40665062]),
  array([       1, 40665062]),
  array([       1, 40665062]),
  array([       1, 40665062]),
  array([       1, 40665062]),
  array([       1, 40665062]),
  array([       1, 40665062]),
  array([       1, 40665062]),
  array([       1, 40665062]),
  array([       1, 40665062])],
 [array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0])],
 [(402338, 18927136, 12363, 976079),
  (402338, 18927136, 12363, 976079),
  (402338, 18927136, 12363, 976079),
  (402338, 18927136, 12363, 976079),
  (402338, 18927136, 12363, 976079),
  (402338, 18927136, 12363, 976079),
  (40

# Testing models.py

In [ ]:
from ddpg_models import *

## Critic

In [ ]:
num_states = env.observation_space.shape[0]
num_actions = env.action_space.shape[0]

critic = Critic(num_states + num_actions, 12, 2)

state, _ = env.reset()
state = np.array(state)
action = env.action_space.sample()

In [ ]:
state_torch = torch.from_numpy(state).to(torch.float32)
action_torch = torch.from_numpy(action).to(torch.float32)
#torch.cat((state_torch, action_torch), 0).shape
print(state_torch.dtype, "---", action_torch.dtype)

torch.float32 --- torch.float32


In [ ]:
critic.forward(state_torch, action_torch)

tensor([  -79303.4297, -1072358.2500], grad_fn=<ViewBackward0>)

## Actor

In [ ]:
actor = Actor(num_states, 12, 2)

actor.forward(state_torch)

tensor([-1.,  1.], grad_fn=<TanhBackward0>)

# Testing ddpg.py

In [ ]:
from ddpg_ddpg import *

ddpg_agent = DDPGagent(env)

In [ ]:
ddpg_agent.get_action(env.observation_space.sample())

-1.0

---

In [ ]:
import numpy as np

listt = np.random.normal(10000, 1000, 1_000_000)
print(np.mean(listt), np.std(listt))

sum_std = 0
sum_mean = 0
listts = np.array_split(listt, 100000)
sum_std = np.array([np.std(listt) for listt in listts])
sum_mean = np.array([np.mean(listt) for listt in listts])
print(np.mean(sum_mean), np.mean(sum_std))

10000.170343165255 999.7670794096549
10000.170343165255 922.3567605257119


---

# Testing classses_n changed

In [ ]:
import numpy as np
from classes_n import *
from init_vars import *

machine = Machine(
            Warehouse(
                Inventory(Demand(P1)),
                Inventory(Demand(P2))
            )
        )

In [ ]:
for i in range(240):
    if machine.t >= machine.finish_time:
        qty = np.random.randint(10_000, 1_000_000)
    print("Day:", machine.t//24)
    print("Hour:", machine.t%24)
    print("Finish time:", machine.finish_time)
    print("Quantity:", qty)
    print("Machine:", machine.produce([0, qty]))
    print("Fulfilled qty error code:", machine.fulfill())
    print("\n----------------\n")

Day: 0
Hour: 0
Finish time: 0
Quantity: 925984
Machine: 0
Fulfilled qty error code: 10

----------------

Day: 0
Hour: 1
Finish time: 58.65507370650142
Quantity: 925984
Machine: 10
Fulfilled qty error code: 10

----------------

Day: 0
Hour: 2
Finish time: 58.65507370650142
Quantity: 925984
Machine: 10
Fulfilled qty error code: 10

----------------

Day: 0
Hour: 3
Finish time: 58.65507370650142
Quantity: 925984
Machine: 10
Fulfilled qty error code: 10

----------------

Day: 0
Hour: 4
Finish time: 58.65507370650142
Quantity: 925984
Machine: 10
Fulfilled qty error code: 10

----------------

Day: 0
Hour: 5
Finish time: 58.65507370650142
Quantity: 925984
Machine: 10
Fulfilled qty error code: 10

----------------

Day: 0
Hour: 6
Finish time: 58.65507370650142
Quantity: 925984
Machine: 10
Fulfilled qty error code: 10

----------------

Day: 0
Hour: 7
Finish time: 58.65507370650142
Quantity: 925984
Machine: 10
Fulfilled qty error code: 10

----------------

Day: 0
Hour: 8
Finish time: 58.65

It seems that is works fine with hour-checking method. 

# Testing environment_dqn

In [ ]:
from environment_dqn_n import *

env = Production_DQN_Env()

In [ ]:
for i in range(241):
    #if observation[3] != 0:
    #    print("Prev:", env.machine.t//24, env.machine.t%24)
    action = env.action_space.sample()
    action = np.array([1, 10])
    observation, reward, done, _, _ = env.step(action)
    if observation[3] != 0:
        print("Day:", env.machine.t//24)
        print("Hour:", env.machine.t%24)
        print("Action:", action)
        print("Current prod order:", env.machine.current_order)
        print("Step:", (observation, reward, done))
        print("\n----------------\n")
    
    env.inc_t()
    if done:
        env.reset()


    exit code prod:  0
    exit code fulf (p1, p2):  (10, 10)
    exit code stor:  10
    service level p1:  0.9999999989999999
    service level p2:  0.9999999989999999
    exit code prod:  10
    exit code fulf (p1, p2):  (10, 10)
    exit code stor:  10
    service level p1:  0.9999999989999999
    service level p2:  0.9999999989999999
    exit code prod:  10
    exit code fulf (p1, p2):  (10, 10)
    exit code stor:  10
    service level p1:  0.9999999989999999
    service level p2:  0.9999999989999999
    exit code prod:  10
    exit code fulf (p1, p2):  (10, 10)
    exit code stor:  10
    service level p1:  0.9999999989999999
    service level p2:  0.9999999989999999
    exit code prod:  10
    exit code fulf (p1, p2):  (10, 10)
    exit code stor:  10
    service level p1:  0.9999999989999999
    service level p2:  0.9999999989999999
    exit code prod:  10
    exit code fulf (p1, p2):  (10, 10)
    exit code stor:  10
    service level p1:  0.9999999989999999
    service level

Observation space:
- machine if free or not: it works
- exit codes for prod, fulf and stor work

Other stuff:
- Time step probably solved.
- Reward works correctly now.

In [ ]:
env.action_space[1].n

5000

# Testing double_dqn_agent

## Testing act function

In [ ]:
from double_dqn_agent import *
from environment_dqn_n import *

env = Production_DQN_Env()
agent = DoubleDQNAgent(5, 2, "test")

In [ ]:
agent.exploration_rate = 0
agent.act()

<bound method DoubleDQNAgent.act of <double_dqn_agent.DoubleDQNAgent object at 0x153836d10>>

---

Testing again DDPG algorithm with the new environment (with bins)

# Testing ddpg_utils.py 
noise may not be necessary for bin version 

In [ ]:
from ddpg.ddpg_utils import *
from environment_dqn_n import *

env = Production_DQN_Env()
gaus = GaussianNoise(env.action_space)

In [ ]:
gaus.get_action(env.action_space.sample())

array([   0., 1694.])

In [ ]:
memory = Memory(1000)
obs_prev, _ = env.reset()

for i in range(100):
    action = env.action_space.sample()
    obs, reward, terminated, _, _ = env.step(action)
    memory.push(obs_prev, action, reward, obs, terminated)
    obs_prev = obs

In [ ]:
memory.sample(10)

([(396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False)],
 [array([   1, 1256]),
  array([   0, 4445]),
  array([  0, 864]),
  array([   0, 4798]),
  array([   0, 2158]),
  array([   1, 2558]),
  array([   1, 3785]),
  array([   1, 1567]),
  array([   1, 2252]),
  array([   1, 1676])],
 [array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0]),
  array([0])],
 [(396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),
  (396029, 18112111, 0, 0, False),

# Testing ddpg_models.py

In [ ]:
from ddpg.ddpg_models import *
from environment_dqn_n import *
import torch

env = Production_DQN_Env()

## Critic

In [ ]:
num_states = env.observation_space.shape[0]
num_actions = env.action_space.shape[0]

critic = Critic(num_states + num_actions, 12, 1)

state, _ = env.reset()
state = torch.FloatTensor(state).unsqueeze(0)
action = torch.FloatTensor(env.action_space.sample()).unsqueeze(0)


In [ ]:
state_torch = torch.from_numpy(state).to(torch.float32)
action_torch = torch.from_numpy(action).to(torch.float32)
#torch.cat((state_torch, action_torch), 0).shape
print(state_torch.dtype, "---", action_torch.dtype)

torch.float32 --- torch.float32


In [ ]:
print(state.shape, "---", action.shape)

torch.Size([1, 5]) --- torch.Size([1, 2])


In [ ]:
critic.forward(state, action)

tensor([[-360518.9688]], grad_fn=<AddmmBackward0>)

## Actor

In [ ]:
actor = Actor(num_states, 12, 2)

actor.forward(state)

p torch.Size([1, 1])
qty torch.Size([1, 1])


tensor([[1.0000e+00],
        [5.0000e+03]], grad_fn=<CatBackward0>)

# Testing ddpg_ddpg.py

In [ ]:
from ddpg.ddpg_ddpg import *
from environment_dqn_n import *

env = Production_DQN_Env()

In [ ]:
agent = DDPGagent(env)

agent.get_action(env.observation_space.sample())

array([[   0., 5000.]], dtype=float32)

# Testing ddpg all together

In [1]:
#import sys
import gym
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ddpg.ddpg_ddpg import DDPGagent
from ddpg.ddpg_utils import *
from environment_dqn_n import *

env = Production_DQN_Env()

agent = DDPGagent(env)
noise = GaussianNoise(env.action_space)
batch_size = 16
rewards = []
avg_rewards = []

for episode in range(10):
    print("Episode:", episode)
    state, _ = env.reset()
    #noise.reset()
    episode_reward = 0
    
    step = 0
    done = False
    while not done:
        print("\tStep:", step)
        step += 1
        action = agent.get_action(state)
        action = noise.get_action(action)
        print("\tAction", action)
        new_state, reward, done, _, _ = env.step(action) 
        agent.memory.push(state, action, reward, new_state, done)
        
        if len(agent.memory) > batch_size:
            agent.update(batch_size)        
        
        state = new_state
        episode_reward += reward

        if done:
            print("episode: {}, reward: {}, average _reward: {} \n".format(episode, np.round(episode_reward, decimals=2), np.mean(rewards[-10:])))
            break

    rewards.append(episode_reward)
    avg_rewards.append(np.mean(rewards[-10:]))

plt.plot(rewards)
plt.plot(avg_rewards)
plt.plot()
plt.xlabel('Episode')
plt.ylabel('Reward')
plt.show()

Episode: 0
	Step: 0
	Action [1 0]
	Step: 1
	Action [1 0]
	Step: 2
	Action [1 0]
	Step: 3
	Action [1 0]
	Step: 4
	Action [1 2]
	Step: 5
	Action [1 0]
	Step: 6
	Action [1 2]
	Step: 7
	Action [1 0]
	Step: 8
	Action [1 1]
	Step: 9
	Action [1 0]
	Step: 10
	Action [1 0]
	Step: 11
	Action [1 3]
	Step: 12
	Action [1 0]
	Step: 13
	Action [1 0]
	Step: 14
	Action [1 1]
	Step: 15
	Action [1 0]
	Step: 16
	Action [1 0]
	Step: 17
	Action [1 2]
	Step: 18
	Action [1 0]
	Step: 19
	Action [1 1]
	Step: 20
	Action [1 3]
	Step: 21
	Action [1 0]
	Step: 22
	Action [1 2]


/Users/alex/Documents/Project_Module/project-module-repo/environment_new_Alex/classes_n.py:348: RuntimeWarning: divide by zero encountered in scalar divide
  varcoef = MACHINE_VARCOEF / np.sqrt(order[1]),
/Users/alex/Documents/Project_Module/project-module-repo/environment_new_Alex/base_functions_n.py:33: RuntimeWarning: divide by zero encountered in log
  mu0 = np.log(mu / np.sqrt(varcoef ** 2 + 1.0))
/Users/alex/Documents/Project_Module/project-module-repo/environment_new_Alex/ddpg/ddpg_ddpg.py:44: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /private/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_5ae0635zuj/croot/pytorch-select_1700511177724/work/torch/csrc/utils/tensor_new.cpp:264.)
  actions = torch.FloatTensor(actions) #.transpose(0,1) # CHANGE HERE IF NECESSARY


	Step: 23
	Action [1 0]
	Step: 24
	Action [1 1]
	Step: 25
	Action [1 0]
	Step: 26
	Action [1 0]
	Step: 27
	Action [1 0]
	Step: 28
	Action [1 1]
	Step: 29
	Action [1 0]
	Step: 30
	Action [1 0]
	Step: 31
	Action [1 0]
	Step: 32
	Action [1 0]
	Step: 33
	Action [1 0]
	Step: 34
	Action [1 1]
	Step: 35
	Action [1 1]
	Step: 36
	Action [1 0]
	Step: 37
	Action [1 0]
	Step: 38
	Action [1 2]
	Step: 39
	Action [1 2]
	Step: 40
	Action [1 0]
	Step: 41
	Action [1 0]
	Step: 42
	Action [1 0]
	Step: 43
	Action [1 0]
	Step: 44
	Action [1 0]
	Step: 45
	Action [1 0]
	Step: 46
	Action [1 0]
	Step: 47
	Action [1 1]
	Step: 48
	Action [1 0]
	Step: 49
	Action [1 0]
	Step: 50
	Action [1 0]
	Step: 51
	Action [1 0]
	Step: 52
	Action [1 1]
	Step: 53
	Action [1 1]
	Step: 54
	Action [1 0]
	Step: 55
	Action [1 0]
	Step: 56
	Action [1 0]
	Step: 57
	Action [1 0]
	Step: 58
	Action [1 0]
	Step: 59
	Action [1 1]
	Step: 60
	Action [1 0]
	Step: 61
	Action [1 0]
	Step: 62
	Action [1 0]
	Step: 63
	Action [1 2]
	Step: 64
	Actio

KeyboardInterrupt: 