In [51]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
from classes_n import *
from main import *


demand_p1 = Demand(P1)

combined_p1 = Inventory(demand_p1)


In [22]:
print(INVENTORY_MODE)

combined_p1.inventory_level


2


[382714]

In [23]:
combined_p1.put(100)
combined_p1.get(50)
combined_p1.inventory_level

[382714, 382764]

### Testing the warehouse

In [72]:
demand_p1, demand_p2 = Demand(P1), Demand(P2)

combined_p1, combined_p2 = Inventory(demand_p1), Inventory(demand_p2)

warehouse = Warehouse(combined_p1, combined_p2)

In [73]:
#order = {"product":"p1", "amount": 40_000_000}
order = [0, 10_000]

In [74]:
warehouse.current_warehouse_level

18090447

In [76]:
warehouse.is_possible_to_store(order)

True

### Testing the Inventory class inside the Warehouse

In [77]:
warehouse.products[1].inventory_level

[17686910]

### Testing Demand class inside the Warehouse

In [78]:
warehouse.products[1].demand_class.demand

array([      0., 1406581.,       0.,  719913.,  677924.,  603457.,
             0.,       0.,       0.,       0.,   89281.,       0.,
             0.,       0., 1086347.,       0.,       0., 3180785.,
        445071.,       0.,  765988.,       0.,  419111.,       0.,
             0.,  455808.,       0.,  124390., 1037908.,       0.,
       3215070.,       0.,       0.,       0., 1135721.,       0.,
        155899., 1323128.,       0.,  539083.,       0., 1941836.,
        369538.,       0.,  686057., 1128795.,       0.,       0.,
        667263.,       0.,  509582.,  674280.,       0.,       0.,
        279732.,       0.,  702633.,       0.,       0., 1280022.,
        856716.,       0.,       0.,  485028.,  835735.,  446885.,
             0.,       0.,       0.,  940311.,  333373.,       0.,
        899582.,       0.,  468743.,  442283.,  751439.,  601159.,
       1889877.,       0., 1198029.,  641432.,       0.,       0.,
       2163658.,       0.,       0.,       0.,  993915.,  4541

### Testing Machine class

In [79]:
machine = Machine(warehouse)

In [80]:
#order = {"product": "p1", "amount": 10_000}
order = [0, 10_000]

In [81]:
machine.is_possible_to_produce(order)

True

In [82]:
machine.produce(order)
machine.produce(order)
machine.produce(order)
machine.produce(order)

0

In [83]:
warehouse.products[0].inventory_level

[403537, 413537, 423537, 433537, 443537]

In [85]:
warehouse.products[1].inventory_level

[17686910, 17686910, 17686910, 17686910, 17686910]

In [87]:
machine.fulfill(10)

10

In [88]:
warehouse.products[0].inventory_level

[403537, 413537, 423537, 433537, 443537]

In [89]:
warehouse.products[1].inventory_level

[17686910, 17686910, 17686910, 17686910, 17686910]

In [39]:
import numpy as np
np.random.lognormal(254.629, 1)
lognorm_int(254.629, 1)

array([78.])

In [40]:
mu0 = 100_000_000 * (0.22/86400)
sigma0 = 10e-5

mu = np.log(mu0**2 / np.sqrt(sigma0**2 + mu0**2))
sigma = np.sqrt(np.log(sigma0**2 / mu0**2 + 1))

print(np.mean(np.random.lognormal(mu, sigma, 100000)))
print(np.mean(lognorm_int(mu0, sigma0, size=100000)))

254.62962948033075
255.0


In [41]:
# Profs code
def lognorm(mu, varcoef) -> float:
    """
    scales the target expected value mu and varcoef = sigma/mu to the 
    embedded normal distribution with mu0 and sigma0 and returns
    the corresponding output
    beauty of lognorm: is always > 0 
    """
    mu0 = np.log(mu / np.sqrt(np.power(varcoef, 2) + 1.0))
    sigma0 = np.sqrt(np.log(np.power(varcoef, 2) + 1.0))
    return random.lognormvariate(mu0, sigma0)

sum = 0
for i in range(100000):
    sum += lognorm(mu0, sigma0)
print(sum/100000)

254.62953253060624


In [42]:
not 1

False

### Testing the environment

In [59]:
from environment_ddpg_n import *

In [60]:
env = Production_DDPG_Env()

In [61]:
env.machine.warehouse.current_warehouse_level

17532820

In [67]:
env.action_space.shape

In [49]:
import gym
from gym import spaces
import numpy as np

test_box = spaces.Box(low=0, high=10, dtype=np.int32)
#possible idea for the action space:
test_box_2 = spaces.Tuple(
    (spaces.Discrete(2), spaces.Box(low=0, high=300000, dtype=np.int32))
)

test_box_3 = spaces.Tuple(
    (spaces.Discrete(2), spaces.Discrete(3))
)

test_box_4 = spaces.Dict(
    {
        "a": spaces.Discrete(2), 
        "b": spaces.Discrete(3)
    }
)

print(spaces.utils.flatdim(test_box_2))
print(spaces.utils.flatten_space(test_box_4))
print(spaces.utils.flatten(test_box_4, test_box_4.sample()))
print(test_box_4.shape)

3
Box(0, 1, (5,), int64)
[1 0 0 1 0]
None


In [ ]:
test_box_2.sample()[1][0]

251453

In [71]:
test_box_5 = spaces.MultiDiscrete([2, 300_000])
test_box_5.sample()

array([     1, 289588])